#!/bin/bash

RUN_DIR=/var/vcap/sys/run/director
LOG_DIR=/var/vcap/sys/log/director
PIDFILE=$RUN_DIR/director.pid

export PATH=/var/vcap/packages/ruby/bin:/var/vcap/packages/genisoimage:$PATH

export TMPDIR=/var/vcap/data/tmp

export C_INCLUDE_PATH=/var/vcap/packages/sqlite/include:/var/vcap/packages/libpq/include:$C_INCLUDE_PATH
export LIBRARY_PATH=/var/vcap/packages/sqlite/lib:/var/vcap/packages/libpq/lib:$LIBRARY_PATH

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    COMPONENT=director erb /var/vcap/jobs/director/config/director.yml.erb > /var/vcap/jobs/director/config/director.yml

    HERE=`pwd`
    cd /var/vcap/packages/director/bosh/director
    chpst -u vcap:vcap bundle exec rake migration:run[/var/vcap/jobs/director/config/director.yml] >>$LOG_DIR/migration.stdout.log 2>>$LOG_DIR/migration.stderr.log

    if [ $? != 0 ]; then
      echo "Migrations failed"
      exit 1
    fi

    cd $HERE

    echo $$ > $PIDFILE

    exec /var/vcap/packages/director/bosh/director/bin/director -c /var/vcap/jobs/director/config/director.yml >>$LOG_DIR/director.stdout.log 2>>$LOG_DIR/director.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: director_ctl {start|stop}" ;;
esac
exit 0
