#!/usr/bin/env ruby
#
require 'fileutils'
require 'yaml'
require 'erb'

def tmpl(src, dst)
  t = nil
  File.open(src, "r") do |file|
    t = file.read
  end
  File.open(dst, "w") do |file|
    template = ERB.new(t)
    file.puts template.result
  end
end

spec = {
  "name" => "director",
  "templates" => {
    "director_ctl" => "bin/director_ctl",
    "director.yml.erb" => "config/director.yml",
  },
  "packages" => ["director", "ruby"]
}

@workers = 5

(1..@workers).each do |i|
  # write template
  @index = i
  tmpl("worker_ctl.erb", "templates/worker_#{i}_ctl")
  tmpl("worker.yml.erb", "templates/worker_#{i}.yml.erb")
  # append to monit
  spec["templates"]["worker_#{i}_ctl"] = "bin/worker_#{i}_ctl"
  spec["templates"]["worker_#{i}.yml.erb"] = "config/worker_#{i}.yml"
end

tmpl("monit.erb", "monit")

# write out spec file
File.open("spec", "w") do |file|
  file.puts spec.to_yaml
end


